### ISSUE TITLE
Performance issues with engine

### ISSUE THREAD

**Issue by r0mainK** [src-d/jgit-spark-connector#351]
## Expected Behavior

Tried to run `apollo bags` on ~12G of siva files (a subset of PGA), on `local-gpu` cluster. Expected the job to run in under two hour, given that on another subset of ~6G it ran in about 40min before failing at a much further point in the job.

## Current Behavior

The job hangs on the last task of the first stage (what would amount to the loading phase). It's been around 5 hours now, and it has still not gone to the next stage. As you can see on this (truncated) snapshot of the spark UI, the last task has been computing for much longer then the other tasks, as if the partition it was considering was completely disproportional in terms of size compared to the others. Although its only the last one that takes forever, the duration of tasks varies a lot. Only 12 out of the 83 tasks took more then 3 mins to finish, but among those 12 tasks 5 of them took between 3 and 5 minutes, and the other took between 10 and 35mins (and the last over 5 hours).

<img width="1254" alt="screen shot 2018-04-02 at 16 54 12" src="https://user-images.githubusercontent.com/32878976/38200936-98c68b36-3696-11e8-8cf3-9b48f6f1eea7.png">

## Possible Solution

Modifying the way the data is inputed, perhaps by tuning the way partitions are made ? I specified the value for `spark.default.parallelism` as 360, but I got only 83 partitions. On the other substet of PGA, I specified the same value, but got 90 partitions, even though the total size was half as big. Tried to play around with that value on my data, and although it seems correlated, the relation is not clear (follows a log curb):

```
Default Parallelism: 200 | 360 |  1200 | 3600 | 10000 
Number of partitions on launch: 46 | 83 | 155 | 238 | 253
```
There are a little over 1000 siva files in this subset so i was expecting to at least be able to have as much partitions. Some of the siva files are quite big, it might also be related ?

## Steps to Reproduce (for bugs)

1. Log on to science 3
2. Run `docker run  -it --rm -v /storage/romain/:/data -v /home/romain/io:/io --link bblfshd --link scylla-egor-1 srcd/apollo_egor apollo bags -r /data --bow /io/bags/bow.asdf --docfreq /io/bags/docfreq.asdf --persist MEMORY_AND_DISK -f graphlet id uast2seq -l Java Python -s 'local[20]' --min-docfreq 5 --bblfsh bblfshd --cassandra scylla-egor-1 -m 40G,80G,6G   --config spark.default.parallelism=360`
3. Press `c` then `Enter`

At first I tried to run it on k8, then copied the siva files and ran it on science3, the behaviours was the same. An error of the form below should pop up, but i don't think it's related.
```
18/04/02 14:53:06 WARN RefWithCommitIterator: incorrect object found
org.eclipse.jgit.errors.IncorrectObjectTypeException: Object c23029f58a8a74e12e99eead288413af578759e5 is not a commit.
``` 

## Context

Not considering [this issue](https://github.com/src-d/engine/issues/348) this will block any attempt to use engine on large amount of data.

## Your Environment (for bugs)

Tried it on science3 with Egor's apollo image (he modified it to fix a couple things in ml), engine version is 0.5.1, as well as `local-gpu` cluster with a custom pod, engine version is 0.5.5.

**Comment by smola** [comment]
Could someone guide us to what stage is it executing when this problem arises? A link to relevant apollo source code lines would help.

**Comment by r0mainK** [comment]
Sure, so when you use `apollo bags` [here](https://github.com/src-d/apollo/blob/7880a9be29c391047442efe86c804c926e7f6967/apollo/bags.py#L89) you are actually using the `ml` function `repos2bow_entry_template`. The `execute` call is [this one](https://github.com/src-d/ml/blob/bfd76c4816ccd4f6bd7efa8211e7b3ee4d240386/sourced/ml/cmd_entries/repos2bow.py#L43), and the trandformers pipe appearing on the terminal at this point is this: ```Ignition -> DzhigurdaFiles -> UastExtractor -> Moder -> Cacher -> MetadataSaver```

(The `cache_hook` is `MetadataSaver` and `select` is `DzhigurdaFiles`, both classes are in the same file in apollo I linked to above).

After looking at the Spark DAG below, I think this problem arises when we are in the `Ignition` phase:
<img width="278" alt="screen shot 2018-04-03 at 14 41 11" src="https://user-images.githubusercontent.com/32878976/38249787-1d3524f2-374d-11e8-95b0-8912de0601a4.png">

**Comment by erizocosmico** [comment]
Shall we close this?

**Comment by r0mainK** [comment]
As you want, but the problem remains. There are workarounds, like converting siva files to parquet, but yeah, as is there is close to no parallelization when loading siva files with the engine, on all tasks Ive seen, and this phase represents usually most of the computing time on a given job. Hopefully this will change whenever gitbase is ready.

**Comment by erizocosmico** [comment]
No, if it remains then we should leave it open. I thought after what Antonio told you to try it was fixed for you.

**Comment by r0mainK** [comment]
No, I edited my answer, sorry will repost next time

**Comment by zurk** [comment]
> There are workarounds, like converting siva files to parquet,

Not really, the problem remains, but it becomes smaller. 
I really hope that we can fix it on our side and make repartition after reading Siva files. 
https://github.com/src-d/ml/pull/228
So the real problem is after reading siva files we have really skewed partitions.

**Comment by sakalouski** [comment]
> As you want, but the problem remains. There are workarounds, like converting siva files to parquet, but yeah, as is there is close to no parallelization when loading siva files with the engine, on all tasks Ive seen, and this phase represents usually most of the computing time on a given job. Hopefully this will change whenever gitbase is ready.

Regarding the .parquet: any ideas how to do that reasonably fast?

**Comment by zurk** [comment]
@sakalouski if you need to use spark you can use `session.read.parquet(parquet_path)` if you do not, there is a bunch of libraries to do that like [pyarrow](https://arrow.apache.org/docs/python/parquet.html) or [fastparquet](https://fastparquet.readthedocs.io/en/latest/).

**Comment by sakalouski** [comment]
@zurk Hi, Konstantin! I meant fast transformation from .siva to .parquet.

**Comment by zurk** [comment]
@sakalouski, oh, ok. You can try to use a sourced-ml python library for that: https://github.com/src-d/ml. There is still a lack of documentation, but what you need is `python3 -m sourced.ml preprocrepos` entry point. It does exactly what you asked: convert `.siva` files to `.parquet`. We use it before all machine learning pipeline. Do not forget to specify which columns you need to save. default list is `("blob_id", "repository_id", "content", "path", "commit_hash", "uast", "lang")` for HEADs only.

**Comment by sakalouski** [comment]
Thanks a lot - sounds simple! Trying it soon and letting You know about the
chosen approach.
At this point I thought of creating an index and accessing particular .siva
files instead of filtering them.

**Comment by sakalouski** [comment]
@zurk for some reason seems not to work for me
![image](https://user-images.githubusercontent.com/32744751/46417146-eb939a00-c720-11e8-8495-33dd2727e4b5.png)
Any ideas, how to fix it?

**Comment by zurk** [comment]
@sakalouski let's move to another issue with it.
Can you please create a new one here https://github.com/src-d/ml/issues and describe exactly what you did, so I can reproduce it and help you? The screenshot is not enough. ;)

**Comment by sakalouski** [comment]
@zurk Hi, I am trying to specify the features to store in parquet, but it does not work (the default version works fine).

The command is the following:
**srcml preprocrepos -r temp -o test_defined_feats --bblfsh x.x.x.x --dep-zip -l Python JavaScript Java -x blob_id repository_id content path commit_hash uast lang &> logfile.txt**

The output is the following:
_srcml preprocrepos: error: argument -x/--mode: invalid choice: 'blob_id' (choose from 'file', 'func', 'repo')_

**Comment by smola** [comment]
@sakalouski Please, do not use this issue for general support. File a new one at https://github.com/src-d/ml/issues

**Comment by r0mainK** [comment]
@smola this should be closed, no ? I don't think know if it's still an issue, but if that's the case another one should be raised, this is completely outdated
