### ISSUE TITLE
ReferencesDataFrame files property

### ISSUE THREAD

**Issue by sakalouski** [src-d/jgit-spark-connector#424]
Using Pyspark with '--packages tech.sourced:engine:0.7.0 pyspark-shell' according to the docs.
```python
engine = Engine(session=spark, repos_path='../go_wspace/github_data/siva/latest/00',repos_format= 'siva')
ref_df= engine.repositories.filter("id='github.com/slashmili/python-jalali'").references.filter("name='refs/pull/10/merge'")
ref_df.files.show() 
```
expected to get **FilesDataFrame**, but _'ReferencesDataFrame' object has no attribute 'files'_
Seems that it is not implemented in the running version.

**Comment by ajnavarro** [comment]
Hi @sakalouski 

You cannot access `files` anymore. You need to get `blobs` or `tree_entries`, depending on what do you want to do.

Don't hesitate to ask if you have some other doubts.

**Comment by sakalouski** [comment]
@ajnavarro Thanks a lot - it worked - got the access to the file contents. 
Do You probably know, how to get _git blame_ data? In other words, I want to get the code of each commit. I could probably do it as difference of previous version and the current one, but do not think that it is the most efficient way. 
Another question: searching over the .siva database, I have noticed that spark uses anomalously tiny portion of resources (10% of all the cores), while on .parquet data it uses around 80-90%. As a result, materializing 1 entry from 3 Gb folder (something.filter().take(1)) takes ~10 seconds. Any ideas, how to fix it?
Thank You!

**Comment by ajnavarro** [comment]
> Do You probably know, how to get git blame data? 

We don't have any specific logic for that. To emulate git blame you should go over a reference history reading the specific file and getting modified lines comparing blob contents and the commit committer name and email (standard git blame is doing basically that).

> Another question: searching over the .siva database, I have noticed that spark uses anomalously tiny portion of resources (10% of all the cores), while on .parquet data it uses around 80-90%. 

When you are processing Siva files, most of the time it will be reading content from that Siva files. Essentially they are git repositories with packfiles, so data is heavily compressed. Also, we parallelize per repository, that means that your process will be as slow as the biggest repository or siva file. I recommend you to preprocess your data and save it to parquet.

**Comment by sakalouski** [comment]
Thanks for the detailed answer!
